// Generated by ChatGPT. It really is useful sometimes 😅
export const articles = [
	{
		id: 1,
		title: "Pokémon 101",
		content:
			"<p>Embark on an epic journey into the world of Pokémon with this comprehensive introductory guide. Discover the diverse array of Pokémon types, from Grass and Water to Fire and Electric. Learn the art of capturing your first Pokémon using Poké Balls and understand the importance of building a well-balanced team.</p><p>As you traverse different regions, immerse yourself in the thrill of Pokémon battles. Grasp the basics of move types, strategy, and effective training techniques. Whether you're a seasoned Trainer or just starting, Pokémon 101 is your gateway to becoming a true Pokémon Master!</p>"
	},
	{
		id: 2,
		title: "Legendary Pokémon Lore",
		content:
			"<p>Delve into the rich tapestry of legendary Pokémon lore with captivating stories about mythical creatures like Mewtwo, Rayquaza, and Arceus. Explore the ancient myths and legends that surround these powerful beings, each with its own unique origin and significance in the Pokémon world.</p><p>From the depths of the ocean to the peaks of the tallest mountains, legendary Pokémon are shrouded in mystery. Uncover the secrets behind their powers, their role in the Pokémon universe, and the awe-inspiring tales that have been passed down through generations of Trainers.</p>"
	},
	{
		id: 3,
		title: "Mastering Pokémon Training",
		content:
			"<p>Embark on a transformative journey at our Pokémon training camp, where aspiring Trainers become true Pokémon Masters. Our camp focuses on honing your training skills, understanding Pokémon behaviors, and fostering a deep connection with your Pokémon companions.</p><p>Learn the art of strategy, effective battling techniques, and the importance of trust between Trainer and Pokémon. With hands-on exercises and guidance from experienced mentors, you'll leave our training camp with the knowledge and skills needed to conquer any challenge that comes your way.</p>"
	},
	{
		id: 4,
		title: "Pokémon Evolution Unveiled",
		content:
			"<p>Uncover the mysteries of Pokémon evolution as we explore the fascinating journey of these creatures. Follow the evolutionary chains that lead Pokémon to transform into more powerful beings, each stage bringing new abilities and characteristics.</p><p>Understand the factors that influence evolution, from friendship and exposure to evolutionary stones to reaching a certain level of experience. Witness the awe-inspiring transformations that occur, and learn how to guide your Pokémon through their evolutionary paths with care and expertise.</p>"
	},
	{
		id: 5,
		title: "Pokémon Breeding Mastery",
		content:
			"<p>Become a Pokémon breeder extraordinaire with our in-depth course on breeding mastery. Delve into the mechanics of Pokémon breeding, discover hidden abilities, and master the art of hatching Pokémon with optimal stats for creating the ultimate team.</p><p>Explore the intricacies of breeding pairs, egg groups, and the impact of various items on the breeding process. With our guidance, you'll not only produce Pokémon with outstanding stats but also forge bonds that go beyond Trainer and Pokémon.</p>"
	},
	{
		id: 6,
		title: "Pokémon Types & Strategies",
		content:
			"<p>Dive deep into the world of Pokémon types and battle strategies to become a true tactician. Learn how to exploit type advantages, counter opponent moves, and craft winning battle tactics that will lead you to victory in every Pokémon battle.</p><p>Whether you're facing a gym leader, participating in a tournament, or challenging the Pokémon League, our comprehensive guide will equip you with the knowledge and skills needed to navigate the complex world of Pokémon battles.</p>"
	},
	{
		id: 7,
		title: "Pokémon Photography Safari",
		content:
			"<p>Embark on an unforgettable Pokémon photography safari, capturing rare moments of Pokémon in their natural habitats. From the bustling forests to the serene beaches, sharpen your photography skills and build a stunning portfolio featuring Pokémon from the adorable Pikachu to the majestic legendary creatures.</p><p>Learn the art of composition, lighting, and patience as you wait for the perfect shot. Join our safari and immerse yourself in the beauty of the Pokémon world through the lens of your camera!</p>"
	},
	{
		id: 8,
		title: "Pokémon Health & Wellness",
		content:
			"<p>Prioritize the well-being of both Trainers and Pokémon with our comprehensive guide to health and wellness. Explore strategies for maintaining physical and mental health during your Pokémon journey, ensuring a strong bond between you and your Pokémon companions.</p><p>Discover the importance of proper nutrition, rest, and mental resilience as you face challenges and triumphs. Balance training with moments of relaxation, creating a sustainable and successful journey as a Pokémon Trainer.</p>"
	},
	{
		id: 9,
		title: "Pokémon Artistry Workshop",
		content:
			"<p>Express your love for Pokémon through art in our exclusive artistry workshop. Join fellow Trainers in exploring various artistic mediums, from drawing and painting to digital creations. Whether you're creating fan art or original masterpieces, unleash your creativity and showcase your unique perspective on the Pokémon universe.</p><p>Receive guidance from experienced artists, share your work with the Pokémon community, and leave the workshop with a portfolio that reflects your passion for the world of Pokémon.</p>"
	},
	{
		id: 10,
		title: "Pokémon Business Ventures",
		content:
			"<p>Explore the exciting world of Pokémon business ventures and turn your passion into a successful enterprise. Learn the ins and outs of running a PokéMart, managing a Gym, or establishing a research lab. Navigate the challenges and opportunities in the Pokémon business landscape, and carve your path to success as an entrepreneur in the Pokémon world.</p><p>From serving the needs of local Trainers to contributing to cutting-edge research, discover the diverse business opportunities available in the Pokémon universe and make your mark as a Pokémon business leader.</p>"
	}
];
