const data = [
  {
    id: 1,
    firstName: "Giulia",
    lastName: "O'Scully",
    email: "goscully0@squidoo.com",
    gender: "Female",
    loyaltyPoints: 557,
    loyaltyCategory: "Silver",
  },
  {
    id: 2,
    firstName: "Onfre",
    lastName: "Raynton",
    email: "oraynton1@gnu.org",
    gender: "Male",
    loyaltyPoints: 51,
    loyaltyCategory: "Bronze",
  },
  {
    id: 3,
    firstName: "Adrien",
    lastName: "Curm",
    email: "acurm2@rambler.ru",
    gender: "Male",
    loyaltyPoints: 1148,
    loyaltyCategory: "Gold",
  },
  {
    id: 4,
    firstName: "Rudy",
    lastName: "Siene",
    email: "rsiene3@ted.com",
    gender: "Genderqueer",
    loyaltyPoints: 192,
    loyaltyCategory: "Bronze",
  },
  {
    id: 5,
    firstName: "Tailor",
    lastName: "McKernan",
    email: "tmckernan4@slate.com",
    gender: "Male",
    loyaltyPoints: 1040,
    loyaltyCategory: "Gold",
  },
  {
    id: 6,
    firstName: "Giffie",
    lastName: "Fibbens",
    email: "gfibbens5@washingtonpost.com",
    gender: "Male",
    loyaltyPoints: 108,
    loyaltyCategory: "Bronze",
  },
  {
    id: 7,
    firstName: "Bertram",
    lastName: "Klimushev",
    email: "bklimushev6@ibm.com",
    gender: "Male",
    loyaltyPoints: 906,
    loyaltyCategory: "Silver",
  },
  {
    id: 8,
    firstName: "Conni",
    lastName: "Brookwell",
    email: "cbrookwell7@dyndns.org",
    gender: "Female",
    loyaltyPoints: 908,
    loyaltyCategory: "Silver",
  },
  {
    id: 9,
    firstName: "Constantine",
    lastName: "Lidster",
    email: "clidster8@webeden.co.uk",
    gender: "Female",
    loyaltyPoints: 923,
    loyaltyCategory: "Silver",
  },
  {
    id: 10,
    firstName: "Gertrud",
    lastName: "Loughman",
    email: "gloughman9@printfriendly.com",
    gender: "Female",
    loyaltyPoints: 196,
    loyaltyCategory: "Bronze",
  },
  {
    id: 11,
    firstName: "Tallulah",
    lastName: "Lenox",
    email: "tlenoxa@seattletimes.com",
    gender: "Female",
    loyaltyPoints: 1055,
    loyaltyCategory: "Gold",
  },
  {
    id: 12,
    firstName: "Myron",
    lastName: "Cruddas",
    email: "mcruddasb@goodreads.com",
    gender: "Male",
    loyaltyPoints: 657,
    loyaltyCategory: "Silver",
  },
  {
    id: 13,
    firstName: "Vivien",
    lastName: "Wimbush",
    email: "vwimbushc@github.com",
    gender: "Female",
    loyaltyPoints: 766,
    loyaltyCategory: "Silver",
  },
  {
    id: 14,
    firstName: "Michelle",
    lastName: "Adnams",
    email: "madnamsd@mediafire.com",
    gender: "Female",
    loyaltyPoints: 921,
    loyaltyCategory: "Silver",
  },
  {
    id: 15,
    firstName: "Mirabelle",
    lastName: "Shapland",
    email: "mshaplande@prweb.com",
    gender: "Female",
    loyaltyPoints: 234,
    loyaltyCategory: "Bronze",
  },
  {
    id: 16,
    firstName: "Shena",
    lastName: "Carmichael",
    email: "scarmichaelf@washington.edu",
    gender: "Female",
    loyaltyPoints: 770,
    loyaltyCategory: "Silver",
  },
  {
    id: 17,
    firstName: "Skipp",
    lastName: "Dmytryk",
    email: "sdmytrykg@wix.com",
    gender: "Male",
    loyaltyPoints: 332,
    loyaltyCategory: "Silver",
  },
  {
    id: 18,
    firstName: "Carce",
    lastName: "Trace",
    email: "ctraceh@weebly.com",
    gender: "Male",
    loyaltyPoints: 136,
    loyaltyCategory: "Bronze",
  },
  {
    id: 19,
    firstName: "Valma",
    lastName: "Dranfield",
    email: "vdranfieldi@tmall.com",
    gender: "Female",
    loyaltyPoints: 985,
    loyaltyCategory: "Silver",
  },
  {
    id: 20,
    firstName: "Jeremie",
    lastName: "Elderbrant",
    email: "jelderbrantj@list-manage.com",
    gender: "Non-binary",
    loyaltyPoints: 180,
    loyaltyCategory: "Bronze",
  },
];
