// An array of people, generated by ChatGPT.
const people = [
  {
    firstName: "Ash",
    lastName: "Ketchum",
    emailAddress: "ash.ketchum@example.com",
    phoneNumbers: [
      { type: "home", number: "123-456-7890" },
      { type: "mobile", number: "987-654-3210" },
    ],
  },
  {
    firstName: "Misty",
    lastName: "Waterflower",
    emailAddress: "misty.waterflower@example.com",
    phoneNumbers: [
      { type: "home", number: "111-222-3333" },
      { type: "office", number: "444-555-6666" },
    ],
  },
  {
    firstName: "Brock",
    lastName: "Rockwell",
    emailAddress: "brock.rockwell@example.com",
    phoneNumbers: [{ type: "mobile", number: "555-123-4567" }],
  },
  {
    firstName: "Serena",
    lastName: "Lumière",
    emailAddress: "serena.lumiere@example.com",
    phoneNumbers: [{ type: "home", number: "777-888-9999" }],
  },
  {
    firstName: "Gary",
    lastName: "Oak",
    emailAddress: "gary.oak@example.com",
    phoneNumbers: [{ type: "office", number: "333-444-5555" }],
  },
  {
    firstName: "May",
    lastName: "Maple",
    emailAddress: "may.maple@example.com",
    phoneNumbers: [{ type: "mobile", number: "999-888-7777" }],
  },
  {
    firstName: "Dawn",
    lastName: "Skye",
    emailAddress: "dawn.skye@example.com",
    phoneNumbers: [{ type: "home", number: "222-333-4444" }],
  },
  {
    firstName: "Cilan",
    lastName: "Sage",
    emailAddress: "cilan.sage@example.com",
    phoneNumbers: [{ type: "office", number: "444-555-6666" }],
  },
  {
    firstName: "Lillie",
    lastName: "Moon",
    emailAddress: "lillie.moon@example.com",
    phoneNumbers: [{ type: "mobile", number: "777-888-9999" }],
  },
  {
    firstName: "Kiawe",
    lastName: "Flame",
    emailAddress: "kiawe.flame@example.com",
    phoneNumbers: [{ type: "home", number: "111-222-3333" }],
  },
];

// console.log(people);

// Find the tbody in the HTML page using querySelector
const tbody = document.querySelector(".person-table > tbody");

// Calls the addPeopleRows function below to add all person rows to the tbody
addPeopleRows(people, tbody);

/**
 * This function adds new rows to the given tbody, containing the information about the given people.
 *
 * @param people the person whose data should be displayed in the table body
 * @param tbody the table body element.
 */
function addPeopleRows(people, tbody) {
  /**
   * Use array's forEach function to loop thru all people in the array, and call the given
   * arrow function for each one. The arrow function will in turn call the addPersonRow() function below.
   *
   * The result is that the addPersonRow() function will be called once for each person in the array.
   */
  people.forEach((person) => addPersonRow(person, tbody));
}

/**
 * This function adds a new row to the given tbody, containing the information about the given person.
 *
 * @param person the person whose data should be displayed in the new row.
 * @param {HTMLElement} tbody the table body element.
 */
function addPersonRow(person, tbody) {
  // Create new row
  const row = document.createElement("tr");

  // Add first name, last name, and email cells using the createTextCell function defined below.
  row.appendChild(createTextCell(person.firstName));
  row.appendChild(createTextCell(person.lastName));
  row.appendChild(createTextCell(person.emailAddress));

  // Create a td containing an ul, which will hold our phone numbers. Append to the tr above.
  const phoneCell = document.createElement("td");
  row.appendChild(phoneCell);
  const phoneList = document.createElement("ul");
  phoneCell.appendChild(phoneList);

  // Loop thru phone numbers using for - of syntax
  for (const phoneNumber of person.phoneNumbers) {
    phoneList.innerHTML += `<li><strong>${phoneNumber.type}:</strong> ${phoneNumber.number}</li>`;
  }

  // Append row to tbody
  tbody.appendChild(row);
}

/**
 * Creates and returns a new table cell with the given text content.
 *
 * @param {string} textContent the text in the cell
 */
function createTextCell(textContent) {
  const td = document.createElement("td");
  td.textContent = textContent;
  return td;
}
